### ISSUE TITLE
Flash/Boot PongoOS After Compiling 

### ISSUE THREAD

**Issue by SecFathy** [checkra1n/pongoOS#118]
I Compiled a PongoOS but I can't find a way to push binary files in a non-jailbroken device after compiling the file

**Comment by Siguza** [comment]
Wdym by "push binary files"?

**Comment by GameM10** [comment]
Having a problem of iOS 15.0 activation lock bypass @Siguza any promises

**Comment by SecFathy** [comment]
Sorry I did not have enough information about this project and I was asking how to use it like checkra1n

**Comment by Siguza** [comment]
It's in the README.

**Comment by iProxys** [comment]
hello, when will jailbreak iOS 15 come out?
