### ISSUE TITLE
error: variable '***' set but not used

### ISSUE THREAD

**Issue by misakazip** [checkra1n/pongoOS#133]
I am using Manjaro Linux, a derivative of Arch Linux, on my Raspberry Pi.
ld64 and cctools are already installed.
An error occurs when I run the `make all` command.
`EMBEDDED_CC=clang EMBEDDED_LDFLAGS=-fuse-ld=/usr/bin/ld64 STRIP=cctools-strip make all `

`src/kernel/mm.c:374:14: error: variable 'vm_index_start' set but not used [-Werror,-Wunused-but-set-variable]
    uint32_t vm_index_start = 0;
             ^
src/kernel/mm.c:934:10: error: variable 'is_tt1' set but not used [-Werror,-Wunused-but-set-variable]
    bool is_tt1 = false;
         ^
2 errors generated.
make: *** [Makefile:99: build/Pongo] error 1`
How can I resolve this error?

**Comment by nick-botticelli** [comment]
Remove `-Werror` from Makefile in the top of the repository
