### ISSUE TITLE
About userland kernel patchfinder

### ISSUE THREAD

**Issue by sen0rxol0** [checkra1n/pongoOS#140]
i'm asking for information on `kpf-test` usage.
Thanks a bunch.

**Comment by Siguza** [comment]
Usage: `./kpf-test [options] path`

Valid options are: `-n` to disable colour output, `-q` to decrease verbosity or `-v` to increase verbosity. `-q` and `-v` may be given multiple times.

The `path` argument must point to either a single kernelcache Mach-O, or a folder containing such files. Symlinks will be followed.

The purpose of `kpf-test` is to provide an as-realistic-as-feasible environment to test the checkra1n kernel patchfinder against thousands of kernels. This means it is actually running the KPF JIT code, so it only works on arm64 hardware (or possibly emulation, if you want to go there). There are builds for macOS and iOS, though the iOS build has only been tested on iOS 12, and IIRC something regarding the JIT memory would have to be changed for iOS 13.
