### ISSUE TITLE
can i have a pongo shell on ios 15?

### ISSUE THREAD

**Issue by dualra1n** [checkra1n/pongoOS#143]
@Siguza when I try to boot pongo os that stuck in "Right before trigger (this is the real bug setup)" so can we boot pongo shell on ios 15?

**Comment by dualra1n** [comment]
if I load an image ibss, lbb or ibec of ios 14, would checkra1n boot pongo os on ios 15? I don't want jailbreak for ios 15 only want to boot pongo os in order to look into about jailbreak

**Comment by Siguza** [comment]
You may or may not have seen this, but we uploaded some bare-bones CLI binaries that can boot PongoOS on a wider range of versions:

```
https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-arm64
https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-armel
https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-x86
https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-x86_64
https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-macos
```

They're lacking all the usual jailbreak stuff, but booting to Pongo should work on most device/version combos. We have some reports of iOS 16.2 not working with some devices, and iOS 7 and 9 basically don't work at all.

**Comment by dualra1n** [comment]
> You may or may not have seen this, but we uploaded some bare-bones CLI binaries that can boot PongoOS on a wider range of versions:
> 
> 
> 
> ```
> 
> https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-arm64
> 
> https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-armel
> 
> https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-x86
> 
> https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-linux-x86_64
> 
> https://assets.checkra.in/downloads/preview/0.1337.0/checkra1n-macos
> 
> ```
> 
> 
> 
> They're lacking all the usual jailbreak stuff, but booting to Pongo should work on most device/version combos. We have some reports of iOS 16.2 not working with some devices, and iOS 7 and 9 basically don't work at all.

Thank you so much and the checkra1n team for this.
