### ISSUE TITLE
Timed out waiting for download mode

### ISSUE THREAD

**Issue by lnguyen234** [checkra1n/pongoOS#156]
Hi,
My device (iPhone 8 iOS16.1) could not be rebooted into Download Mode after initially loading PongoOS. Does anyone have the same issue?
Thanks

**Comment by Siguza** [comment]
Can you try replugging cable when the timeout is logged?

**Comment by lnguyen234** [comment]
yes I did, but the phone went straight to normal mode after being disconnected

**Comment by nexplorer-3e** [comment]
> yes I did, but the phone went straight to normal mode after being disconnected

@lnguyen234 hello how do you solve the issue?
