### ISSUE TITLE
PongoOS image is too large: must be at most 0x7fe00, have 0xa5060

### ISSUE THREAD

**Issue by zoe-vb** [checkra1n/pongoOS#160]
Having compiled a custom version of PongoOS and loaded it with -cpE -k Pongo.bin the 1337 build of checkra1n gives the error 
PongoOS image is too large: must be at most 0x7fe00, have 0xa5060

**Comment by Siguza** [comment]
You built the `master` branch, 1337 builds require the `iOS15` branch.
