### ISSUE TITLE
quick question do i have permission to use some or your code in the repo's on this org?

### ISSUE THREAD

**Issue by espero-dev** [checkra1n/pongoOS#162]
i wannt to use some code to make checkrain windows version it will be 50 cpp and 50 c

**Comment by Siguza** [comment]
The code in this repository is licensed under a mix of MIT, BSD, Apache, APSL and Public Domain. Some code (libfdt, newlib) is dual- or multi-licensed, but we are using those in accordance with the BSD license.

So it's all licensed under a permissive OSS license with no copyleft.
