### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by uncor3** [checkra1n/pongoOS#189]
MacOS Sonoma 14.0 i386 (non M) Xcode 15.4 | MacOSX14.5.sdk | iPhoneOS17.5.sdk

Build fails for some reason I've specified all versions above 

I have tried doing `make -C newlib distclean; make -C newlib all` but didn't help

Any help is greatly appreciated 

![image](https://github.com/user-attachments/assets/c9e11de1-07cc-4d56-9079-948593724b88)

**Comment by Siguza** [comment]
I think this means you're building the `master` branch... do you actually want that, or do you wanna build the `iOS15` branch? It shouldn't happen there.

Either way, `EMBEDDED_CFLAGS=-Wno-error` should work for the master branch.

**Comment by uncor3** [comment]
Never realized that I was supposed to clone iOS15 branch. After cloning  and running make all worked fine thank you
