### ISSUE TITLE
USBControlTransfer error

### ISSUE THREAD

**Issue by Athja** [checkra1n/pongoOS#27]
everytime i do "./pongoterm" it says "connected" then "USBControlTransfer: (iokit/usb) pipe has stalled, error needs to be cleared" and doesnt give a shell. Why is this happening?

**Comment by Athja** [comment]
also after like a minute it randomly boots into ios

**Comment by woachk** [comment]
Hello,

do you use a new pongoOS too?

**Comment by Athja** [comment]
yes

**Comment by IIWare** [comment]
I have the same issue too.

**Comment by YCarlB** [comment]
I have the same issue too.

**Comment by Siguza** [comment]
What version of PongoOS are you using? (Should be printed at the top of the screen on your device.)

**Comment by IIWare** [comment]
@Siguza I will find out because I have the same issue.

**Comment by IIWare** [comment]
@Siguza my version:
`pongoOS 1.3.0-2e7eb6bc (EL1)`
and I still have this issue: USBControlTransfer: (iokit/usb) pipe has stalled, error needs to be cleared

**Comment by woachk** [comment]
@IIWare That's... way too old for this feature.

You can use ./checkra1n -p -k Pongo.bin with building a new pongoOS from this repo.

**Comment by IIWare** [comment]
@woachk so I do /Applications/checkra1n.app/contents/MacOS/checkra1n -p -k <insert pongo.bin filepath here> ? or the Pongo.bin will just export?

**Comment by Siguza** [comment]
```
git clone https://github.com/checkra1n/pongoOS.git
cd pongoOS
make
path/to/checkra1n -k build/Pongo.bin
```

**Comment by IIWare** [comment]
@Siguza finally! this helped!

**Comment by Athja** [comment]
yes this worked. thank you
