### ISSUE TITLE
Booting pongoOS.

### ISSUE THREAD

**Issue by TylerJaacks** [checkra1n/pongoOS#37]
After building pongoOS how do I run it on my device?

**Comment by Siguza** [comment]
`checkra1n -k`

**Comment by TylerJaacks** [comment]
So I need to put my phone into DFU and then run checkra1n -k?

**Comment by Siguza** [comment]
Yes.

**Comment by TylerJaacks** [comment]
This should provide a good framework if I wanted to port or build an operating system for the idevices. Also sorry for the noob questions and thanks for all the hard work.

**Comment by sen0rxol0** [comment]
Hi @Siguza, is there any way to boot pongoOS w/o `checkra1n` ?

edit: `ra1npoc` might be the way.
