### ISSUE TITLE
'make all' doesn't build checkra1n-kpf-pongo and PongoConsolidated.bin

### ISSUE THREAD

**Issue by marijuanARM** [checkra1n/pongoOS#46]
Trying to compile the latest pongoOS with the kpf included, but looks like `make all` is only building Pongo & Pongo.bin. AFAIK, `make all` should build the kpf, so could this be looked at? Thanks.

building on macOS Catalina w/ Xcode & CLT installed, btw.

**Comment by Siguza** [comment]
Fixed in 765f75c0fd3b0da87f49b9f32de443d007da1cd9.  
We temporarily removed img4lib due to potential licensing issues. It has been replaced with a new implementation now.
