### ISSUE TITLE
Can we get somewhere to submit community made modules?

### ISSUE THREAD

**Issue by Witherking25** [checkra1n/pongoOS#7]

**Comment by kpwn** [comment]
this is a good idea, maybe like a wiki kind of thing?

**Comment by Aboood412** [comment]
> https://github.com/checkra1n/pongoOS/issues/7#issue-578857619

**Comment by blacktop** [comment]
So github itself lets you do this via repo keywords which can then be grouped into topics like so: https://github.com/topics/pongoos. You can see how @NyaMisty did it here https://github.com/NyaMisty/PongoHelper and if people ⭐️ the cream will float to the top

**Comment by woachk** [comment]
https://github.com/checkra1n/pongoModules
